version: '3'

volumes:
  DMD_db:

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/DMD_db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'dj_my_do_db'
       MYSQL_USER: 'kirill'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
